version: '3'
services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=pro

  server:
    restart: always
    container_name: pro-server
    image: maaaaaaaaad/pro-server:0.1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=9999
      - TTL=60
      - LIMIT=10
      - CACHE_DB_HOST=localhost
      - CACHE_DB_PORT=6379
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_USER_PASSWORD=12345
      - DB_NAME=pro
    ports:
      - '8888:9999'
    depends_on:
      - db
