version: '3'

services:
  db:
    image: mysql
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=pro
      - MYSQL_ROOT_PASSWORD=12345
      - TZ=Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
